gpu_id: 0
train_data_dir_path: C:\Noam\Code\vision_course\downloads\datasets\300W-LP\300W-3D
test_data_dir_path: C:\Noam\Code\vision_course\downloads\datasets\300W-LP\300W-3D
file_name_list: C:\Noam\Code\vision_course\downloads\datasets\300W-LP\rel_paths.txt
#snapshot_path: C:\Noam\Code\vision_course\hopenet\models\hopenet_robust_alpha1.pkl
#snapshot_path:  C:\Noam\Code\vision_course\hopenet\deep-head-pose\code\original_code_augmented\output\snapshots\output_epoch_1.pkl
snapshot_path:  C:\Noam\Code\vision_course\hopenet\deep-head-pose\code\original_code_augmented\output\snapshots\original_train_epoch_25.pkl
#snapshot_path: C:\Noam\Code\vision_course\hopenet\deep-head-pose\code\original_code_augmented\output\cloud_snapshots\original_train_epoch_30.pkl


batch_size_test: 1
batch_size_train: 16
num_epochs: 5
save_viz: True
dataset: Pose_300W_LP
create_paths_file_at: C:\Noam\Code\vision_course\downloads\datasets\300W-LP\rel_paths.txt
output_string: output
face_detector_path: C:\Noam\Code\vision_course\hopenet\models\mmod_human_face_detector.dat
scale_percent: 100.0

output_dir: C:\Noam\Code\vision_course\hopenet\output
#output_dir: C:\Noam\Code\vision_course\hopenet\output_alpha_robust
output_model_dir: output\models