learning_rate: 0.00001
alpha: 0.001
gpu_id: 0
#train_data_dir_path: C:\Noam\Code\vision_course\downloads\datasets\300W-LP\300W-3D
train_data_dir_path: C:\Noam\Code\vision_course\downloads\datasets\300W-LP\big_set\300W_LP

file_name_list: C:\Noam\Code\vision_course\downloads\datasets\300W-LP\big_set\300W_LP\rel_paths.txt
snapshot_path: ""
train_percentage: 95.0
seed: 17

batch_size_test: 1
batch_size_train: 16
num_epochs: 30
save_viz: True
dataset: Pose_300W_LP
create_paths_file_at: C:\Noam\Code\vision_course\downloads\datasets\300W-LP\rel_paths.txt
output_string: output
face_detector_path: C:\Noam\Code\vision_course\hopenet\models\mmod_human_face_detector.dat
scale_percent: 100.0

output_dir: C:\Noam\Code\vision_course\hopenet\output_holdout
#output_dir: C:\Noam\Code\vision_course\hopenet\output_alpha_robust
output_model_dir: output\models